# Generated by Django 3.2 on 2021-04-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.TextField(default=4),
            preserve_default=False,
        ),
    ]
