# Generated by Django 3.2 on 2021-05-17 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210427_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 10, 40, 27, 54070)),
        ),
    ]
